# Generated by Django 4.2.25 on 2025-10-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                ("score_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "Score",
            },
        ),
        migrations.CreateModel(
            name="ExamHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.FloatField()),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
            options={
                "db_table": "ExamHistory",
            },
        ),
    ]
