# Generated by Django 4.2.25 on 2025-10-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("choice", "选择题"),
                            ("true_false", "判断题"),
                            ("fill_in_blank", "填空题"),
                            ("essay", "简答题"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Question",
            },
        ),
    ]
