# Generated by Django 4.2.25 on 2025-10-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="choice_type",
            field=models.CharField(
                blank=True,
                choices=[("single", "单选题"), ("multiple", "多选题")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="essay_answer",
            field=models.TextField(blank=True, help_text="简答题参考答案", null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="fill_answer",
            field=models.TextField(blank=True, help_text="填空题标准答案", null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="options",
            field=models.JSONField(blank=True, help_text="选择题选项，JSON格式存储", null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="true_false_answer",
            field=models.BooleanField(blank=True, help_text="判断题答案", null=True),
        ),
    ]
