# Generated by Django 4.2.25 on 2025-10-30 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.AutoField(primary_key=True, serialize=False)),
                ("exam_name", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "Exam",
            },
        ),
        migrations.CreateModel(
            name="ExamQuestion",
            fields=[
                (
                    "exam_question_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="exams.exam"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "db_table": "ExamQuestion",
            },
        ),
    ]
